### ISSUE TITLE
Mache ich was falsch?

### ISSUE THREAD

**Issue by Sagestum** [MrFlamez/Wurzelimperium-Bot#4]
Login scheint leider nicht mehr zu klappen, hier die Ausgabe: 

`Initialize WurzelBot...
Traceback (most recent call last):
  File "console.py", line 137, in <module>
    main()
  File "console.py", line 14, in main
    init()
  File "console.py", line 50, in init
    wurzelBot.launchBot(server, user, pw)
  File "/home/parallels/git/Wurzelimperium-Bot/src/WurzelBot.py", line 128, in launchBot
    self.productData.initAllProducts()
  File "/home/parallels/git/Wurzelimperium-Bot/src/Produktdaten.py", line 90, in initAllProducts
    self.__setAllPricesOfNPC()
  File "/home/parallels/git/Wurzelimperium-Bot/src/Produktdaten.py", line 43, in __setAllPricesOfNPC
    coins.setPriceNPC((300.0))
AttributeError: 'NoneType' object has no attribute 'setPriceNPC'
`

**Comment by MrFlamez** [comment]
Danke für Dein Feedback.
Der Login hat funktioniert, sonst wärst Du nicht soweit gekommen. ;) Ich muss mir das mal genauer ansehen. Kommentier mal in der Produktdaten.py die Zeilen 42 und 43 aus. Das Kommentarzeichen ist die Raute #.
